name: Build Debian package (Ubuntu 24.04)

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-24.04
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev fakeroot rsync

      - name: Make packaging script executable
        run: |
          if [ -f ./scripts/build-deb.sh ]; then chmod +x ./scripts/build-deb.sh; else echo "No build script found"; exit 1; fi

      - name: Build .deb
        run: ./scripts/build-deb.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ./artifacts/*.deb
